# Generated by Django 3.1.13 on 2021-07-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_backend-base-page-nonabstract_20210516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='banner_content',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='footer_content',
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.TextField(default='', verbose_name='alt'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_image', to='website.image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='news',
            name='preamble',
            field=models.TextField(default='', verbose_name='preamble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='banner_content_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='banner_content_en', to='website.contentcollection', verbose_name='english banner content'),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='banner_content_sv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='banner_content_sv', to='website.contentcollection', verbose_name='swedish banner content'),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='footer_content_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='footer_content_en', to='website.contentcollection', verbose_name='english footer content'),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='footer_content_sv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='footer_content_sv', to='website.contentcollection', verbose_name='swedish footer content'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='image'),
        ),
    ]
