version: '2.4'

networks:
    backend-net:

services:
  backend:
    build:
        context: ..
        dockerfile: .devcontainer/Dockerfile.Dev
    image: fsh:backend-dc
    volumes:
        - ../:/app/server/
        - ./local.py:/app/server/project_settings/local.py
    ports:
        - 8000:8000/tcp
    networks:
        - backend-net
    # Needed by devcontainer to keep it alive.
    command: /bin/sh -c "while sleep 1000; do :; done"

  mariadb:
    image: linuxserver/mariadb:alpine
    environment:
        - MYSQL_USER=fdev
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=hemsidan_db
        - TZ=Europe/Stockholm
    expose:
        - 3306
    networks:
        - backend-net

  adminer:
        image: dockette/adminer:mysql
        ports:
            - 8003:80
        volumes:
            - ./adminer.css:/srv/adminer.css:ro
        networks:
            - backend-net
